// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jhpxfvwhcxakzajioxiz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpocHhmdndoY3hha3phamlveGl6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzE3OTI2NjksImV4cCI6MjA4NzM2ODY2OX0.-4soKb5wlgrEQtsfFecDO9RgtImIymcb5RcoY2r2IH0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});